headings:
  tasks: "Tasks"
  challenges: "Challenges"
  solutions: "Solutions"
  decisions_made: "Decisions Made"
  learnings: "Learnings"
  next_steps: "Next Steps"
  additional_notes: "Additional Notes"
  conclusion: "conclusion"
